language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    secure: HB25gX2eFNASvJM9qpgWCD1+WNktQkmAAVNADcE5g48vR3ZbtUohTkWbFVxMjDTV6hOTnvXgg2+uoxM5CI+lkhnLnIK4JOs8ISvJoTaco1EXLkxY+L61QCXHHTCGgO6urCimGBZW38/i7fYVb3VB0e9jfOSxOZHJ9/A8w9z9WLdqareBp3hJOJ/wkyaS3Wf/3a4hk03bVijZ1//Asr4Z2ts1fHP5yWSZNWL7fKbzmZVBJYQG+1w8HLmISFQJkUH3Giqy+/DotFZvocd48quRKw00VidIypTsYeiY/VLS2lcSwgUYvuA6Knyeqq+aNsaj3gNtXLEByKaUagibLyihNdgvD4v59lWjmAsvOddWKpxJ9epvy7TEKo9iK1Trfmy1mm24M3qlB6SR0CL1DIaBLbJvRYkmKzYoxaTDokA4QCaE5bhRQCaaDkNcmWcowpD29/QiPM+QRhDvBX9tggQgm4Ehzc7UL6KAU3Nm+1ChSYAPuJ+/mr/37wcyTnle9sasosHo9pEu7WFV05rB9eAeWDrpIB7ULfPHW8eZNbV5rVLdwbICkiQqJLhxSdzg+oSmp7AJRwCQ8OTK/S+bd/A5t4jyUgUrj87IwoRszgCD0SweKgTy6ME5D+FPpdjMWDJfTqaQk+mISRIJseYQvCnOC9R/ssMj83f0e6H61NRcbuA=
